// This file is @generated by prost-build.
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct Event {
    #[prost(uint32, tag = "1")]
    pub sensor_id: u32,
    #[prost(message, optional, tag = "3")]
    pub ts: ::core::option::Option<::prost_types::Timestamp>,
    #[prost(double, tag = "2")]
    pub gyro_x: f64,
    #[prost(double, tag = "4")]
    pub gyro_y: f64,
    #[prost(double, tag = "5")]
    pub gyro_z: f64,
    #[prost(double, tag = "6")]
    pub accel_x: f64,
    #[prost(double, tag = "7")]
    pub accel_y: f64,
    #[prost(double, tag = "8")]
    pub accel_z: f64,
}
