services:
    flux_events:
        image: clickhouse:latest
        cap_add:
            - SYS_NICE
            - NET_ADMIN
            - IPC_LOCK
        ulimits:
            nofile:
                soft: 262144
                hard: 262144
        volumes:
            # /etc/clickhouse-server/config.d/*.xml - files with server configuration adjustments
            # /etc/clickhouse-server/users.d/*.xml - files with user settings adjustments
            - ./db/init-db.sh:/docker-entrypoint-initdb.d/init-db.sh
            - ./ch_logs:/var/log/clickhouse-server/
            - eventsdata:/var/lib/clickhouse/
        environment:
            - CLICKHOUSE_USER=${CLICKHOUSE_USER:-skju_flux_dev}
            - CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT=1
            - CLICKHOUSE_PASSWORD=${CLICKHOUSE_PASSWORD:-skju_flux_dev_change_me}
        #ports:
        #    - "9000:9000" # tcp clickhouse
        restart: unless-stopped

volumes:
    eventsdata:
